dividendo = int( input("Entre com o dividendo:\n"))
divisor = int( input("Entre com o divisor:\n"))
print("Dividendo:",dividendo)
print("Divisor:",divisor)
print("Quociente:",dividendo//divisor)
print("Resto:",dividendo % divisor)